spring:
  datasource:
    url: jdbc:${DB_TYPE}://${DB_ADDR}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: ${DB_DRIVER}
  jpa:
    database: ${DB_TYPE}
    hibernate:
      ddl-auto: create
server:
  port: 8081
