spring:
  thymeleaf:
    prefix: classpath:/mail-templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: juhyeon0928
    password: gmvknhmqxayqjiii
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
